export const CATEGORY = "CATEGORY";

export const ADDMYLISTSUCCESS = "ADDMYLISTSUCCESS";

export const ADDMYLISTNUMBER = "ADDMYLISTNUMBER";

export const ADDBUTTONTOGGLE = "ADDBUTTONTOGGLE";

export const REMOVEMYLISTSUCCESS = "REMOVEMYLISTSUCCESS";

export const REMOVEBUTTONTOGGLE = "REMOVEBUTTONTOGGLE";

export const REMOVEMYLISTNUMBER = "REMOVEMYLISTNUMBER";
